# Settings

Main_command: "blockmirror|mirror"
# If you want player get for example always grasblock
#, no matter what tool he use.
Silk_touch: false
Tools:
  Marker_tool:
    Matrial: STICK
    Display_name: "&fMark the locations"
    Lore:
      - "&aSet locations you want to mirror"
      - "&a"
      - "&aChange item or drop this to"
      - "&aturn it off."
Patterns:
  Circle:
    # fill all blocks within the pattern if set to true.
    Fill_all_blocks: false
    Settings:
      Fill_blocks:
        Passive:
          Matrial: ANDESITE
          Display_name: "&fFill blocks"
          Lore:
            - "&aClick to activate if"
            - "&ayou want to fill all"
            - "&ablocks, in the pattern."
        Active:
          Matrial: POLISHED_ANDESITE
          Display_name: "&fFill blocks"
          Lore:
            - "&aClick to deactivate if"
            - "&ayou not want to fill all"
            - "&ablocks, in the pattern."
      Change_facing:
        Passive:
          Matrial: OAK_SAPLING
          Display_name: "&fChange facing."
          Lore:
            - "&aClick to activate if"
            - "&ayou want to change the"
            - "&afacing of the block"
            - " "
            - "&aCurrent set:&6 {1}"
        Active:
          Matrial: OAK_LOG
          Display_name: "&fChange facing."
          Lore:
            - "&aClick to deactivate if"
            - "&ayou not want to change the"
            - "&afacing of the block"
            - " "
            - "&aCurrent set:&6 {1}"
    Passive:
      Matrial: OAK_SIGN
      Display_name: "&fCircle pattern"
      Lore:
        - "&aLeft-click to set this pattern"
      Glow: true
    Active:
      Matrial: DARK_OAK_SIGN
      Display_name: "&fCircle pattern"
      Lore:
        - "&aRight-click to unset this pattern"
      Glow: false
  Square:
    # fill all blocks within the pattern if set to true.
    Fill_all_blocks: false
    Settings:
      Fill_blocks:
        Passive:
          Matrial: ANDESITE
          Display_name: "&fFill blocks"
          Lore:
            - "&aClick to activate if"
            - "&ayou want to fill all"
            - "&ablocks, in the pattern."
        Active:
          Matrial: POLISHED_ANDESITE
          Display_name: "&fFill blocks"
          Lore:
            - "&aClick to deactivate if"
            - "&ayou not want to fill all"
            - "&ablocks, in the pattern."
      Change_facing:
        Passive:
          Matrial: OAK_SAPLING
          Display_name: "&fChange facing."
          Lore:
            - "&aClick to activate if"
            - "&ayou want to change the"
            - "&afacing of the block"
            - " "
            - "&aCurrent set:&6 {1}"
        Active:
          Matrial: OAK_LOG
          Display_name: "&fChange facing."
          Lore:
            - "&aClick to deactivate if"
            - "&ayou not want to change the"
            - "&afacing of the block"
            - " "
            - "&aCurrent set:&6 {1}"
    Passive:
      Matrial: STONE
      Display_name: "&fSquare pattern"
      Lore:
        - "&aLeft-click to set this pattern"
      Glow: true
    Active:
      Matrial: STONE_BRICKS
      Display_name: "&fSquare pattern"
      Lore:
        - "&aRight-click to unset this pattern"
      Glow: false